name: every_read
version: 0.1.1
description: "A Flutter project for read different document formats on different platforms"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  pdfrx: ^1.0.97
  file_picker: ^8.1.6
  flutter_bloc: ^8.1.6
  rename_app: ^1.6.1
  flutter_launcher_icons: ^0.14.2
  shared_preferences: ^2.3.4
  json_annotation: ^4.9.0
  permission_handler: ^11.3.1
  path_provider: ^2.1.5
  xml: ^6.5.0
  equatable: ^2.0.7
  package_info_plus: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.2


flutter:
  uses-material-design: true
  assets:
    - assets/icons/logo.png